### ISSUE TITLE
Error: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by ghost** [lucascaro/hexo-deployer-sftp#8]
I use a private key in the format ed25519

But this type of private key does not seem to be supported, have you considered adding it?

**Comment by noraj** [comment]
This hexo package is just a wrapper around https://github.com/dobbydog/sftp-sync-deploy, so if something not working with a key format it must be an upstream issue.

**Comment by suyinLoong** [comment]
`err: Error: Cannot parse privateKey: Unsupported key format`
我也遇到了同样的问题
